### ISSUE TITLE
Get exact epoch end time

### ISSUE THREAD

**Issue by APPLECHOI** [forbole/flowJuno#10]
## Feature description 
Since epoch end at approximately 12:00 pm PT on Tuesday (7:00 pm UTC). There are possibilities that the epoch not end on time due to some accident or upgrade. The variance in epoch length to be less than 2 hours for a 1-week epoch (~1%). Therefore, there should be some additional operation to monitor the epoch changes.

## Implementation proposal
[This](https://docs.onflow.org/staking/epoch-preparation/#phase-transitions) explains how epoch changes. 
The system should monitor the transaction about [flowEpoch.endEpoch()](https://github.com/onflow/flow-core-contracts/blob/136d1f9a3ba68e1ff4c4d3d71fa869785fa1b36e/contracts/epochs/FlowEpoch.cdc#L392) in real time

**Comment by APPLECHOI** [comment]
May look at [payreward()](https://github.com/onflow/flow-core-contracts/blob/d68b4f26950001e76aa722ad24e1a4e6aa5079b9/contracts/FlowIDTableStaking.cdc#L862) to listen to the reward emmitted events

**Comment by APPLECHOI** [comment]
Do an additional operation to monitor if the last ~100 blocks have EpochTotalRewardsPaid event emitted. If yes, do the node operator/delegator balance scan. @kwunyeung do you think it is a good idea?

**Comment by kwunyeung** [comment]
Is it possible to track the reward payout transaction?

**Comment by APPLECHOI** [comment]
@kwunyeung Yes
There are Events emitted when having reward payout transactions:
- RewardsPaid(nodeID: rewardBreakdown.nodeID, amount: nodeReward) that check reward payout for every node individually.
- DelegatorRewardsPaid(nodeID: rewardBreakdown.nodeID, delegatorID: delegator, amount: delegatorReward) check reward for every delegator individually
- EpochTotalRewardsPaid(total: totalRewards, fromFees: fromFees, minted: mintedRewards, feesBurned: rewardsVault.balance) 
-  NewEpoch(totalStaked: FlowIDTableStaking.getTotalStaked(), totalRewardPayout: FlowIDTableStaking.epochTokenPayout) The new payout is calculated and changed before this method is executed and will not be changed for the rest of the epoch
- ... brunch of events about staking(TokensUnstaking,TokenStaking...) before newEpoch is emitted

We can scan NewEpoch event emitted in the last ~50 blocks like every ~1 minute. Once that is emitted, do the balance scan. Is that good?

**Comment by APPLECHOI** [comment]
Or we can do it for every block parsed. If NewEpoch event is in the block, do the balance scan. I think that is not good especially when flowjuno is parsing old blocks. It will scan so many time when parsing old block, but that is at the same epoch.

**Comment by kwunyeung** [comment]
@HarleyAppleChoi what do you mean 
> but that is at the same epoch

for the old blocks?

**Comment by APPLECHOI** [comment]
Scanning latest validators and delegators status. If the trigger is just finding event message at block parsing event instead of fetching event at latest blocks, the latest status may get scan so many times when parsing old block.

**Comment by kwunyeung** [comment]
Do you know which epoch would it be when you see the event in previous blocks?

**Comment by APPLECHOI** [comment]
@kwunyeung  Yes but the gRPC endpoints for Flow are unstable when executing scripts from old states [See here](https://github.com/onflow/flow-go-sdk/issues/213#issuecomment-988914711). Even we find an end epoch event on some block, we cannot require the state on that epoch yet

**Comment by kwunyeung** [comment]
I see. For the old state, I think we can copy those data from some existing public data, e.g, another explorer.

**Comment by APPLECHOI** [comment]
[Flowscan](https://flowscan.org/staking/history) seems don't have historical data for validators but only 
- Total Rewards
- Total Staked
- APY (w/o fee)
Any other places that save public history?

**Comment by kwunyeung** [comment]
Let’s ping the FLOW team and see how they can be retrieved.
