### ISSUE TITLE
issue with mainnet5 when enqueueing missing block of 12023475+

### ISSUE THREAD

**Issue by stuntnmore** [forbole/flowJuno#19]
![image](https://user-images.githubusercontent.com/6933360/152952574-05343419-5aa7-4880-b20b-77470a6800ed.png)

having an issue where when its enqueueing missing blocks after a specific height after 12023475+ it starts getting a invalid memory address error.

**Comment by APPLECHOI** [comment]
That is because unprocessed collections are not handled properly.
