### ISSUE TITLE
Mainnet 16 Bugs

### ISSUE THREAD

**Issue by APPLECHOI** [forbole/flowJuno#21]
error="fail to get locked account address :client: failed to construct cadence.Value entity from protobuf value: convert: json-cdc: failed to decode valid JSON structure: EOF"

**Comment by HarleyAppleChoi** [comment]
error="fail to get locked account address :client: failed to construct cadence.Value entity from protobuf value: convert: json-cdc: failed to decode valid JSON structure: EOF"

**Comment by APPLECHOI** [comment]
It's solved
