### ISSUE TITLE
Implenment module/pruning 

### ISSUE THREAD

**Issue by APPLECHOI** [forbole/flowJuno#9]
## Feature description 

For now, pruning is disabled. It would hopefully improve performance once implemented.

## Implementation proposal

Implement pruning modules like [juno](https://github.com/forbole/juno/blob/9314a50579552300f56182d1e3dfb014f835b3bf/modules/pruning/module.go#L46) does

**Comment by kwunyeung** [comment]
@HarleyAppleChoi do you have in mind how the pruning will be implemented?

**Comment by APPLECHOI** [comment]
@kwunyeung  Not yet. Is that similar to database pruning, which deletes the old data and archive?

**Comment by APPLECHOI** [comment]
Just turn out we didn't use that at all in juno anyway. Delete that
